name: hisnelmoslem
description: A new Flutter project.

publish_to: "none"

version: 2.5.1+19

environment:
  # sdk: ">=2.12.0 <3.0.0"
  # sdk: ">=2.18.5 <3.0.0"
  sdk: ">=3.0.0 <4.0.0"

dependency_overrides:
  intl: ^0.18.0

dependencies:
  audioplayers: ^3.0.0
  auto_size_text: ^3.0.0
  awesome_notifications: ^0.7.4+1
  clipboard: ^0.1.3

  cupertino_icons: ^1.0.4
  day_night_time_picker: ^1.0.5
  enum_to_string: ^2.0.1
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  flutter_local_notifications: ^13.0.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.1.6
  flutter_slidable: ^2.0.0
  flutter_zoom_drawer: ^3.0.1
  fluttertoast: ^8.0.8
  font_awesome_flutter: ^10.1.0
  get: ^4.6.5
  get_storage: ^2.0.3
  intl: ^0.18.0
  material_design_icons_flutter: ^6.0.7096
  path: ^1.8.2
  path_provider: ^2.0.8
  rxdart: ^0.27.3
  share: ^2.0.4
  shared_preferences: ^2.2.2
  sleek_circular_slider: ^2.0.1
  sqflite: ^2.0.2
  timelines: ^0.1.0
  url_launcher: ^6.1.7
  vibration: ^1.7.4-nullsafety.0
  wakelock: ^0.6.1+1

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  lint: ^2.1.2

flutter_native_splash:
  android: true
  ios: true
  web: true
  color: "#303030"

flutter:
  uses-material-design: true

  assets:
    - assets/json/
    - assets/images/
    - assets/quran/
    - assets/sounds/
    - assets/db/

  fonts:
    - family: Uthmanic
      fonts:
        - asset: assets/fonts/uthmanic_hafs_ver12.otf
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
    - family: Marhey
      fonts:
        - asset: assets/fonts/Marhey-Regular.ttf
    - family: Vazirmatn
      fonts:
        - asset: assets/fonts/Vazirmatn-Regular.ttf
    - family: ElMessiri
      fonts:
        - asset: assets/fonts/ElMessiri-Regular.ttf
    - family: Harmattan
      fonts:
        - asset: assets/fonts/Harmattan-Regular.ttf
    - family: Lateef
      fonts:
        - asset: assets/fonts/Lateef-Regular.ttf
    - family: Mada
      fonts:
        - asset: assets/fonts/Mada-Regular.ttf
    - family: Changa
      fonts:
        - asset: assets/fonts/Changa-Regular.ttf
    - family: ArefRuqaa
      fonts:
        - asset: assets/fonts/ArefRuqaa-Regular.ttf
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
    - family: NotoNastaliqUrdu
      fonts:
        - asset: assets/fonts/NotoNastaliqUrdu-Regular.ttf
    - family: Lalezar
      fonts:
        - asset: assets/fonts/Lalezar-Regular.ttf
    - family: ReemKufi
      fonts:
        - asset: assets/fonts/ReemKufi-Regular.ttf
    - family: Rakkas
      fonts:
        - asset: assets/fonts/Rakkas-Regular.ttf
